services:
  hackerhub-front:
    image: nginx:alpine
    container_name: hackerhub-front
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
